EkbJob.Application/Models/ErrorViewModel.cs
using System;

namespace EkbJob.Application.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EkbJob.Application/Models/VmResume.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EkbJob.Application.Views
{
    public class VmResume
    {
        [Key]
        public Guid ResumeId { get; set; }

        /// <summary>
        /// Имя и возраст
        /// </summary>
        [Required]
        [Display(Name = "Имя и возраст")]
        public string NameAndAge { get; set; }

        /// <summary>
        /// Должность
        /// </summary>
        /// [Required]
        [Display(Name = "Должность")]
        public string Vacancy { get; set; }

        /// <summary>
        /// Город
        /// </summary>
        [Display(Name = "Город")]
        public string City { get; set; }

        /// <summary>
        /// Цена
        /// </summary>
        [Display(Name = "Цена")]
        public string Price { get; set; }

        /// <summary>
        /// Опыт работы
        /// </summary>
        [Display(Name = "Опыт работы")]
        public string Practise { get; set; }

        /// <summary>
        ///  Образование
        /// </summary>
        [Display(Name = "Образование")]
        public string Education { get; set; }

        /// <summary>
        /// Спарсенная информация
        /// </summary>
        [Display(Name = "Спарсено?")]
        public bool Parsed { get; set; }
    }
}

EkbJob.Application/Controllers/ResumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using EkbJob.Application.Services.Interface;
using EkbJob.Application.Views;
using EkbJob.Database.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EkbJob.Application.Controllers
{
    public class ResumeController : Controller
    {
        readonly IMapper _mapper;
        IRepository<Resume> _repository;
        public ResumeController(IMapper mapper, IRepository<Resume> repository)
        {
            _mapper = mapper;
            _repository = repository;
        }

        // GET: Resume
        public ActionResult Index()
        {
            var list = _repository.GetAll();
            var models = list.Select(x => _mapper.Map<VmResume>(x)).ToList();
            return View(models);
        }

        // GET: Resume/Parse
        public async Task<ActionResult> Parse([FromServices]IParseService parserService)
        {
            _repository.DeleteAll();
            await parserService.ParseAsync();
            return RedirectToAction("Index");
        }
    }
}

EkbJob.Application/Views/Resume/Index.cshtml
@model IEnumerable<EkbJob.Application.Views.VmResume>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Parse">Спарсить</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NameAndAge)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Vacancy)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.City)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Practise)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Education)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Parsed)
                </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NameAndAge)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vacancy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Practise)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Education)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Parsed)
            </td>
        </tr>
}
    </tbody>
</table>

EkbJob.Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EkbJob.Application</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Resume" asp-action="Index" class="navbar-brand">EkbJob</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Resume" asp-action="Index">Резюме</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - EkbJob.Application</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>